<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- This is the correct property -->
    <OutputPath>..\..\gameroot\bin\</OutputPath>

    <!-- Remove net10.0 folder -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <!-- Remove Debug/Release folder -->
    <AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>

    <!-- Remove RID folder -->
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

  </PropertyGroup>

  <!-- Auto-include generated enums -->
  <ItemGroup>
      <Compile Include="Generated\*.generated.cs">
          <Link>Generated\%(Filename)%(Extension)</Link>
      </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Matrix4x4Interop.cs" />
    <Compile Include="QuaternionInterop.cs" />
    <Compile Include="Vector2Interop.cs" />
    <Compile Include="Vector3Interop.cs" />
    <Compile Include="MessageCodec.cs" />
    <Compile Include="ScriptMessageInterop.cs" />
    <Compile Include="ScriptMessageParser.cs" />
    <Compile Include="ScriptRuntime.cs" />
  </ItemGroup>

  <!-- Optional: keep folder visible in Solution Explorer -->
  <ItemGroup>
    <Folder Include="Generated\">
      <ExcludeFromClean>true</ExcludeFromClean>
    </Folder>
  </ItemGroup>

  <Target Name="CleanGeneratedFiles" BeforeTargets="CoreClean">
    <ItemGroup>
      <FilesToClean Include="Generated\*.generated.cs" />
    </ItemGroup>
    <Delete Files="@(FilesToClean)" ContinueOnError="true" />
    <Message Text="XGE: Deleted generated files before CoreClean." Importance="high" />
  </Target>

</Project>
